### ISSUE TITLE
Attempting to upload nonexistent file crashes client

### ISSUE THREAD

**Issue by coderobe** [oxy-secure/oxy#116]
Specifying a file path that doesn't exist as argument to `upload` crashes the client with
```rust
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', libcore/result.rs:945:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook
             at libstd/panicking.rs:227
   3: oxy::ui::Ui::create::{{closure}}
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:515
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:426
   6: rust_begin_unwind
             at libstd/panicking.rs:337
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:92
   8: core::result::unwrap_failed
   9: oxy::core::metacommands::<impl oxy::core::Oxy>::handle_metacommand
  10: <T as transportation::notify::Notifiable>::notify
  11: oxy::ui::Ui::send
  12: <oxy::ui::Ui as transportation::notify::Notifiable>::notify
  13: <transportation::buffered_transport::BufferedTransport as transportation::notify::Notifiable>::notify
  14: transportation::scheduler::run
  15: oxy::run
  16: std::rt::lang_start::{{closure}}
  17: main
  18: __libc_start_main
  19: _start
```

In comparison, `download` handles the error and throws a warning:
```
WARN 2018-06-25T17:45:53Z: oxy::ui: Download request rejected: "Failed to stat"
```

Ideally, `upload` should handle it the same way download does, and not fatally crash the client.

**Comment by jennamagius** [comment]
Thanks! There's definitely a handful of lazy unwrap()s that still need cleanup. Identifying where they are is very helpful :)

**Comment by jennamagius** [comment]
Fixed in dev: https://github.com/oxy-secure/oxy/commit/8de5c0f592ae4e090f4b9fa60f11583838a5f78a

Thanks again!
